import type {
  ActivityHistoryItem,
  Competition,
  Goal,
  Message,
  Notification,
  Post,
  PowerPlay,
  User,
} from "./types";

const hoursAgo = (h: number) => new Date(Date.now() - h * 3600 * 1000).toISOString();
const daysAgo = (d: number) => hoursAgo(d * 24);
const hoursFromNow = (h: number) => new Date(Date.now() + h * 3600 * 1000).toISOString();
const daysFromNow = (d: number) => hoursFromNow(d * 24);

export const USERS: User[] = [
  {
    id: "u-maya",
    name: "Maya Chen",
    handle: "mayasprints",
    avatarColor: "linear-gradient(135deg,#1379c9,#35c2f2)",
    avatarInitials: "MC",
    focus: ["running", "consistency"],
    bio: "5K PR chaser. Sunrise miles only. Coach @ Ridgeline TC.",
    score: 4820,
    streak: 41,
    followers: 1204,
    following: 318,
    location: "Denver, CO",
    points: 1340,
    freezes: 2,
  },
  {
    id: "u-dre",
    name: "Andre Walsh",
    handle: "drewalsh",
    avatarColor: "linear-gradient(135deg,#ff3b5c,#ffc23d)",
    avatarInitials: "AW",
    focus: ["strength", "basketball"],
    bio: "Strength coach. Rim protector on weekends. 405 club.",
    score: 5310,
    streak: 63,
    followers: 2011,
    following: 220,
    location: "Austin, TX",
    points: 1820,
    freezes: 1,
  },
  {
    id: "u-sam",
    name: "Sam Ibarra",
    handle: "samplays",
    avatarColor: "linear-gradient(135deg,#35c2f2,#0b3f7a)",
    avatarInitials: "SI",
    focus: ["golf", "mobility"],
    bio: "Scratch handicap in progress. Mobility over everything.",
    score: 3120,
    streak: 12,
    followers: 640,
    following: 402,
    location: "Scottsdale, AZ",
    points: 640,
    freezes: 0,
  },
  {
    id: "u-priya",
    name: "Priya Nair",
    handle: "priyalifts",
    avatarColor: "linear-gradient(135deg,#c8ff3d,#3dd6ff)",
    avatarInitials: "PN",
    focus: ["strength", "nutrition"],
    bio: "Powerlifter. 3x meet competitor. Macros nerd.",
    score: 6042,
    streak: 88,
    followers: 3402,
    following: 190,
    location: "Brooklyn, NY",
    points: 2450,
    freezes: 3,
  },
  {
    id: "u-jonah",
    name: "Jonah Ricci",
    handle: "jricci",
    avatarColor: "linear-gradient(135deg,#ffc23d,#ff3b5c)",
    avatarInitials: "JR",
    focus: ["steps", "habits", "recovery"],
    bio: "10K steps or it didn't happen. Recovery is training.",
    score: 2790,
    streak: 27,
    followers: 512,
    following: 349,
    location: "Chicago, IL",
    points: 890,
    freezes: 1,
  },
  {
    id: "u-tasha",
    name: "Tasha Brooks",
    handle: "tashab",
    avatarColor: "linear-gradient(135deg,#0b3f7a,#35c2f2)",
    avatarInitials: "TB",
    focus: ["running", "strength"],
    bio: "Marathon #4 loading. Hybrid athlete. Show up, stand out.",
    score: 5590,
    streak: 55,
    followers: 1877,
    following: 264,
    location: "Portland, OR",
    points: 1975,
    freezes: 2,
  },
  {
    id: "u-devon",
    name: "Devon Okafor",
    handle: "devono",
    avatarColor: "linear-gradient(135deg,#ff8a3d,#ffc23d)",
    avatarInitials: "DO",
    focus: ["basketball", "consistency"],
    bio: "Rec league legend. Working on the left hand.",
    score: 1980,
    streak: 9,
    followers: 288,
    following: 501,
    location: "Charlotte, NC",
    points: 410,
    freezes: 0,
  },
];

export const GOALS: Goal[] = [
  {
    id: "g-pushup-streak",
    title: "100 Push-Ups Daily",
    category: "strength",
    mode: "goal",
    description: "Build a bulletproof upper body with a daily 100 push-up minimum, rain or shine.",
    target: "100",
    unit: "push-ups / day",
    durationDays: 30,
    startDate: daysAgo(12),
    endDate: daysFromNow(18),
    status: "active",
    progress: 62,
    streak: 12,
    coverGradient: "linear-gradient(135deg,#0b3f7a,#35c2f2)",
    participants: [
      { userId: "me", progress: 62, joinedAt: daysAgo(12), isOwner: true, lastLoggedAt: hoursAgo(14) },
      { userId: "u-dre", progress: 88, joinedAt: daysAgo(12), isOwner: false },
      { userId: "u-priya", progress: 95, joinedAt: daysAgo(11), isOwner: false },
      { userId: "u-devon", progress: 40, joinedAt: daysAgo(9), isOwner: false },
    ],
  },
  {
    id: "g-half-marathon",
    title: "Half Marathon Build",
    category: "running",
    mode: "quest",
    description: "12-week progressive mileage build toward a sub-1:45 half marathon.",
    target: "13.1",
    unit: "mile race",
    durationDays: 84,
    startDate: daysAgo(30),
    endDate: daysFromNow(54),
    status: "active",
    progress: 38,
    streak: 6,
    coverGradient: "linear-gradient(135deg,#1379c9,#3dd6ff)",
    participants: [
      { userId: "me", progress: 38, joinedAt: daysAgo(30), isOwner: true, lastLoggedAt: daysAgo(1) },
      { userId: "u-maya", progress: 71, joinedAt: daysAgo(30), isOwner: false },
      { userId: "u-tasha", progress: 64, joinedAt: daysAgo(28), isOwner: false },
    ],
  },
  {
    id: "g-scratch-golf",
    title: "Break 80",
    category: "golf",
    mode: "goal",
    description: "Shave four strokes off the handicap before the fall member-guest.",
    target: "79",
    unit: "strokes",
    durationDays: 60,
    startDate: daysAgo(20),
    endDate: daysFromNow(40),
    status: "active",
    progress: 45,
    streak: 3,
    coverGradient: "linear-gradient(135deg,#0f5132,#c8ff3d)",
    participants: [
      { userId: "u-sam", progress: 58, joinedAt: daysAgo(20), isOwner: true },
      { userId: "me", progress: 45, joinedAt: daysAgo(18), isOwner: false, lastLoggedAt: daysAgo(3) },
    ],
  },
  {
    id: "g-10k-steps",
    title: "10K Steps Streak",
    category: "steps",
    mode: "challenge",
    description: "Group accountability challenge — hit 10,000 steps every day this month.",
    target: "10,000",
    unit: "steps / day",
    durationDays: 30,
    startDate: daysAgo(9),
    endDate: daysFromNow(21),
    status: "active",
    progress: 80,
    streak: 9,
    coverGradient: "linear-gradient(135deg,#ffc23d,#ff3b5c)",
    stake: 100,
    pot: 400,
    participants: [
      { userId: "u-jonah", progress: 100, joinedAt: daysAgo(9), isOwner: true, stakePaid: 100 },
      { userId: "me", progress: 80, joinedAt: daysAgo(9), isOwner: false, lastLoggedAt: hoursAgo(20), stakePaid: 100 },
      { userId: "u-devon", progress: 66, joinedAt: daysAgo(9), isOwner: false, stakePaid: 100 },
      { userId: "u-tasha", progress: 90, joinedAt: daysAgo(8), isOwner: false, stakePaid: 100 },
    ],
  },
  {
    id: "g-mobility-reset",
    title: "Daily Mobility Reset",
    category: "mobility",
    mode: "goal",
    description: "10 minutes of mobility work every morning before caffeine.",
    target: "10",
    unit: "minutes / day",
    durationDays: 21,
    startDate: daysAgo(5),
    endDate: daysFromNow(16),
    status: "active",
    progress: 55,
    streak: 5,
    coverGradient: "linear-gradient(135deg,#3dd6ff,#c8ff3d)",
    participants: [
      { userId: "u-sam", progress: 70, joinedAt: daysAgo(5), isOwner: true },
      { userId: "me", progress: 55, joinedAt: daysAgo(5), isOwner: false, lastLoggedAt: daysAgo(2) },
    ],
  },
  {
    id: "g-bench-duel",
    title: "Bench Press Duel",
    category: "strength",
    mode: "duel",
    description: "Head to head — most weight added to 1RM bench over 6 weeks.",
    target: "+20",
    unit: "lb added",
    durationDays: 42,
    startDate: daysAgo(14),
    endDate: daysFromNow(28),
    status: "active",
    progress: 33,
    streak: 4,
    coverGradient: "linear-gradient(135deg,#ff3b5c,#0b3f7a)",
    stake: 250,
    pot: 500,
    isPublic: true,
    participants: [
      { userId: "u-priya", progress: 61, joinedAt: daysAgo(14), isOwner: true, stakePaid: 250 },
      { userId: "u-dre", progress: 33, joinedAt: daysAgo(14), isOwner: false, stakePaid: 250 },
    ],
  },
  {
    id: "g-freethrow-duel",
    title: "Free Throw Streak Duel",
    category: "basketball",
    mode: "duel",
    description: "Head to head — most consecutive makes out of 50 attempts, logged daily.",
    target: "50",
    unit: "makes / 50",
    durationDays: 21,
    startDate: daysAgo(2),
    endDate: daysFromNow(19),
    status: "active",
    progress: 20,
    streak: 2,
    coverGradient: "linear-gradient(135deg,#ff8a3d,#ff3b5c)",
    stake: 150,
    pot: 150,
    isPublic: true,
    participants: [{ userId: "u-devon", progress: 20, joinedAt: daysAgo(2), isOwner: true, stakePaid: 150 }],
  },
  {
    id: "g-clean15-nutrition",
    title: "Clean 15 Nutrition Challenge",
    category: "nutrition",
    mode: "challenge",
    description: "15 straight days of on-plan meals. Group accountability, no cheat-meal excuses.",
    target: "15",
    unit: "clean days",
    durationDays: 15,
    startDate: daysAgo(4),
    endDate: daysFromNow(11),
    status: "active",
    progress: 27,
    streak: 4,
    coverGradient: "linear-gradient(135deg,#c8ff3d,#0f5132)",
    stake: 75,
    pot: 225,
    isPublic: true,
    participants: [
      { userId: "u-tasha", progress: 27, joinedAt: daysAgo(4), isOwner: true, stakePaid: 75 },
      { userId: "u-maya", progress: 33, joinedAt: daysAgo(4), isOwner: false, stakePaid: 75 },
      { userId: "u-sam", progress: 20, joinedAt: daysAgo(3), isOwner: false, stakePaid: 75 },
    ],
  },
  {
    id: "g-mindful-mornings",
    title: "Mindful Mornings Quest",
    category: "recovery",
    mode: "quest",
    description: "8 weeks of a 10-minute breathwork + mobility ritual before the day starts.",
    target: "56",
    unit: "morning sessions",
    durationDays: 56,
    startDate: daysAgo(6),
    endDate: daysFromNow(50),
    status: "active",
    progress: 11,
    streak: 6,
    coverGradient: "linear-gradient(135deg,#3dd6ff,#0b3f7a)",
    isPublic: true,
    participants: [{ userId: "u-jonah", progress: 11, joinedAt: daysAgo(6), isOwner: true }],
  },
];

export const POSTS: Post[] = [
  {
    id: "p-1",
    userId: "u-priya",
    goalId: "g-pushup-streak",
    type: "streak",
    headline: "88-day streak alert",
    body: "Day 88 of push-ups done before the sun's even up. This one's a lifestyle now.",
    statValue: "88",
    statLabel: "day streak",
    createdAt: hoursAgo(2),
    reactions: [
      { emoji: "\u{1F525}", userIds: ["u-dre", "u-maya", "me"] },
      { emoji: "\u{1F4AA}", userIds: ["u-tasha"] },
    ],
    comments: [
      { id: "c-1", userId: "u-dre", text: "This is disgusting (in a good way). Keep going.", createdAt: hoursAgo(1) },
    ],
  },
  {
    id: "p-2",
    userId: "u-maya",
    goalId: "g-half-marathon",
    type: "progress",
    headline: "Tempo run: 6 miles @ 7:42 pace",
    body: "Negative split the last two miles. Half marathon build is clicking.",
    statValue: "6.0 mi",
    statLabel: "tempo",
    createdAt: hoursAgo(5),
    reactions: [{ emoji: "\u{1F3C3}", userIds: ["me", "u-tasha", "u-jonah"] }],
    comments: [],
  },
  {
    id: "p-3",
    userId: "u-devon",
    goalId: "g-10k-steps",
    type: "win",
    headline: "First 10K day of the challenge",
    body: "Late-night walk to close the ring. Don't judge the method, judge the result.",
    createdAt: hoursAgo(7),
    reactions: [{ emoji: "\u{1F44F}", userIds: ["u-jonah", "me"] }],
    comments: [
      { id: "c-2", userId: "u-jonah", text: "Whatever it takes. Welcome to the club.", createdAt: hoursAgo(6) },
    ],
  },
  {
    id: "p-4",
    userId: "u-dre",
    goalId: "g-bench-duel",
    type: "competition-result",
    headline: "Closed the gap in the bench duel",
    body: "+8lb this week. Priya's still out front but the duel is heating up.",
    statValue: "+8 lb",
    statLabel: "this week",
    createdAt: hoursAgo(10),
    reactions: [{ emoji: "\u{26A1}", userIds: ["u-priya", "me"] }],
    comments: [],
  },
  {
    id: "p-5",
    userId: "u-tasha",
    type: "encouragement",
    headline: "Shoutout to this whole rally",
    body: "Y'all have made 5am so much easier to get out of bed for. Show up, stand out — truly.",
    createdAt: hoursAgo(14),
    reactions: [
      { emoji: "\u{2764}\u{FE0F}", userIds: ["u-maya", "u-dre", "u-priya", "me", "u-jonah"] },
    ],
    comments: [],
  },
  {
    id: "p-6",
    userId: "u-sam",
    goalId: "g-scratch-golf",
    type: "progress",
    headline: "Carded a 76 at Troon",
    body: "New season low. The break-80 goal is finally feeling real.",
    statValue: "76",
    statLabel: "strokes",
    createdAt: daysAgo(1),
    reactions: [{ emoji: "\u{26F3}", userIds: ["me"] }],
    comments: [
      { id: "c-3", userId: "me", text: "Let's go! That short game work is paying off.", createdAt: hoursAgo(20) },
    ],
  },
  {
    id: "p-7",
    userId: "u-jonah",
    type: "streak",
    headline: "27 days of 10K+ steps",
    body: "Longest streak I've ever put together. Recovery walks count double.",
    statValue: "27",
    statLabel: "day streak",
    createdAt: daysAgo(1),
    reactions: [{ emoji: "\u{1F525}", userIds: ["u-devon", "u-tasha"] }],
    comments: [],
  },
  {
    id: "p-8",
    userId: "u-priya",
    type: "powerplay",
    powerPlayId: "pp-pushup-48",
    headline: "Powering into the 48-Hour Push-Up Power Play",
    body: "412 reps in and counting. This event brings out something different.",
    statValue: "412",
    statLabel: "reps",
    createdAt: daysAgo(1),
    reactions: [{ emoji: "\u{1F4A5}", userIds: ["u-dre", "me"] }],
    comments: [],
  },
];

export const COMPETITIONS: Competition[] = [
  {
    id: "comp-pushup-streak",
    title: "100 Push-Ups Daily — Standings",
    description: "Ranked by completion rate across the 30-day push-up goal.",
    metric: "completion",
    category: "strength",
    mode: "challenge",
    endsAt: daysFromNow(18),
    leaderboard: [
      { userId: "u-priya", rank: 1, score: 95, delta: 2, metricLabel: "95% complete" },
      { userId: "u-dre", rank: 2, score: 88, delta: 1, metricLabel: "88% complete" },
      { userId: "me", rank: 3, score: 62, delta: -1, metricLabel: "62% complete" },
      { userId: "u-devon", rank: 4, score: 40, delta: 0, metricLabel: "40% complete" },
    ],
  },
  {
    id: "comp-10k-steps",
    title: "10K Steps Streak — Standings",
    description: "Group challenge ranked by current daily streak.",
    metric: "streak",
    category: "steps",
    mode: "challenge",
    endsAt: daysFromNow(21),
    leaderboard: [
      { userId: "u-jonah", rank: 1, score: 27, delta: 1, metricLabel: "27 day streak" },
      { userId: "u-tasha", rank: 2, score: 19, delta: 1, metricLabel: "19 day streak" },
      { userId: "me", rank: 3, score: 9, delta: 1, metricLabel: "9 day streak" },
      { userId: "u-devon", rank: 4, score: 6, delta: -2, metricLabel: "6 day streak" },
    ],
  },
  {
    id: "comp-bench-duel",
    title: "Bench Press Duel",
    description: "Priya vs. Andre — most weight added to 1RM bench over 6 weeks.",
    metric: "improvement",
    category: "strength",
    mode: "duel",
    endsAt: daysFromNow(28),
    leaderboard: [
      { userId: "u-priya", rank: 1, score: 61, delta: 5, metricLabel: "+12.2 lb" },
      { userId: "u-dre", rank: 2, score: 33, delta: 8, metricLabel: "+6.6 lb" },
    ],
  },
  {
    id: "comp-global-score",
    title: "Global Ascend Score",
    description: "All-time score across every goal, streak, and competition.",
    metric: "rank",
    category: "consistency",
    mode: "challenge",
    endsAt: daysFromNow(90),
    leaderboard: [
      { userId: "u-priya", rank: 1, score: 6042, delta: 3, metricLabel: "6,042 pts" },
      { userId: "u-dre", rank: 2, score: 5310, delta: -1, metricLabel: "5,310 pts" },
      { userId: "u-tasha", rank: 3, score: 5590, delta: 1, metricLabel: "5,590 pts" },
      { userId: "u-maya", rank: 4, score: 4820, delta: 0, metricLabel: "4,820 pts" },
      { userId: "me", rank: 5, score: 2410, delta: 2, metricLabel: "2,410 pts" },
      { userId: "u-jonah", rank: 6, score: 2790, delta: -1, metricLabel: "2,790 pts" },
      { userId: "u-devon", rank: 7, score: 1980, delta: 0, metricLabel: "1,980 pts" },
    ],
  },
];

export const POWER_PLAYS: PowerPlay[] = [
  {
    id: "pp-pushup-48",
    title: "48-Hour Push-Up Power Play",
    tagline: "Max reps, open to everyone. No excuses, no gym required.",
    category: "strength",
    rules: [
      "Log push-up sets any time during the 48-hour window.",
      "Sets must be in reps of 10+ to count toward your total.",
      "Leaderboard updates live as reps are logged.",
      "Top 3 earn the Power Play badge on their profile.",
    ],
    startsAt: hoursAgo(20),
    endsAt: hoursFromNow(28),
    unit: "reps",
    isLive: true,
    participantIds: ["u-priya", "u-dre", "u-devon", "me", "u-tasha"],
    leaderboard: [
      { userId: "u-priya", rank: 1, score: 412, delta: 34, metricLabel: "412 reps" },
      { userId: "u-dre", rank: 2, score: 388, delta: 20, metricLabel: "388 reps" },
      { userId: "u-tasha", rank: 3, score: 305, delta: 15, metricLabel: "305 reps" },
      { userId: "me", rank: 4, score: 240, delta: 40, metricLabel: "240 reps" },
      { userId: "u-devon", rank: 5, score: 190, delta: 10, metricLabel: "190 reps" },
    ],
    coverGradient: "linear-gradient(135deg,#0b3f7a,#ff3b5c)",
  },
  {
    id: "pp-weekend-steps",
    title: "Weekend Step Power Play",
    tagline: "Most steps logged Saturday–Sunday. Walk, hike, run — it all counts.",
    category: "steps",
    rules: [
      "Window opens Saturday 12:00am and closes Sunday 11:59pm.",
      "Sync or manually log steps any time during the window.",
      "Ties are broken by earliest final submission.",
    ],
    startsAt: daysFromNow(3),
    endsAt: daysFromNow(5),
    unit: "steps",
    isLive: false,
    participantIds: ["u-jonah", "u-tasha"],
    leaderboard: [
      { userId: "u-jonah", rank: 1, score: 0, delta: 0, metricLabel: "Not started" },
      { userId: "u-tasha", rank: 2, score: 0, delta: 0, metricLabel: "Not started" },
    ],
    coverGradient: "linear-gradient(135deg,#ffc23d,#3dd6ff)",
  },
  {
    id: "pp-most-improved",
    title: "7-Day Most Improved",
    tagline: "Biggest week-over-week jump across any tracked goal wins.",
    category: "custom",
    rules: [
      "Improvement is measured against your prior 7-day average.",
      "Any active goal category is eligible.",
      "Self-reported progress is trust-based — rally accountability applies.",
    ],
    startsAt: hoursAgo(70),
    endsAt: hoursAgo(2),
    unit: "% improvement",
    isLive: false,
    participantIds: ["u-sam", "u-maya", "u-jonah"],
    leaderboard: [
      { userId: "u-sam", rank: 1, score: 34, delta: 0, metricLabel: "+34%" },
      { userId: "u-maya", rank: 2, score: 22, delta: 0, metricLabel: "+22%" },
      { userId: "u-jonah", rank: 3, score: 18, delta: 0, metricLabel: "+18%" },
    ],
    coverGradient: "linear-gradient(135deg,#c8ff3d,#1379c9)",
  },
];

export const NOTIFICATIONS: Notification[] = [
  {
    id: "n-1",
    type: "powerplay-start",
    message: "48-Hour Push-Up Power Play is live — you're in 4th place.",
    createdAt: hoursAgo(1),
    read: false,
  },
  {
    id: "n-2",
    type: "reaction",
    actorId: "u-dre",
    message: "Andre Walsh reacted \u{1F525} to your push-up streak.",
    createdAt: hoursAgo(3),
    read: false,
  },
  {
    id: "n-3",
    type: "rank-change",
    message: "You moved up to #3 in the 10K Steps Streak challenge.",
    createdAt: hoursAgo(9),
    read: true,
  },
  {
    id: "n-4",
    type: "streak-risk",
    message: "Your Daily Mobility Reset streak is at risk — log today before midnight.",
    createdAt: hoursAgo(11),
    read: false,
  },
  {
    id: "n-5",
    type: "rally-invite",
    actorId: "u-sam",
    message: "Sam Ibarra invited you to rally on Break 80.",
    createdAt: daysAgo(2),
    read: true,
  },
];

export const ACTIVITY_HISTORY: ActivityHistoryItem[] = [
  { id: "h-1", userId: "me", label: "Logged 100 push-ups", detail: "Day 12 of 100 Push-Ups Daily", createdAt: hoursAgo(14) },
  { id: "h-2", userId: "me", label: "Ran 4.2 miles", detail: "Half Marathon Build — easy pace", createdAt: daysAgo(1) },
  { id: "h-3", userId: "me", label: "Joined Break 80", detail: "Invited by Sam Ibarra", createdAt: daysAgo(18) },
  { id: "h-4", userId: "me", label: "Hit 10,412 steps", detail: "10K Steps Streak — day 9", createdAt: daysAgo(1) },
  { id: "h-5", userId: "me", label: "Completed mobility reset", detail: "10 minutes — hip + ankle focus", createdAt: daysAgo(2) },
];

export const MESSAGES: Message[] = [
  {
    id: "m-1",
    threadId: "u-sam",
    senderId: "u-sam",
    text: "Hey! Saw you joined Break 80 — down to play Saturday morning if you're free?",
    createdAt: daysAgo(2),
  },
  {
    id: "m-2",
    threadId: "u-priya",
    senderId: "u-priya",
    text: "88 days and counting on the push-up streak 😤 you're right behind me, don't slow down now.",
    createdAt: hoursAgo(9),
  },
];

export function userById(id: string): User | undefined {
  if (id === "me") return undefined;
  return USERS.find((u) => u.id === id);
}
